apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        volumeMounts:
          - name: phpmyadmin-volume
            mountPath: /etc/todos
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql-service"
        - name: PMA_PORT
          value: "3306"
      volumes:
        - name: phpmyadmin-volume
          persistentVolumeClaim:
              claimName: phpmyadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: phpmyadmin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpmyadmin-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: phpmyadmin-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: phpmyadmin-pv
